apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sambaro.fullname" . }}
  labels:
{{ include "sambaro.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sambaro.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sambaro.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          ports:
            - name: smb
              containerPort: 445
              protocol: TCP
          livenessProbe:
            exec:
              command: ["smbstatus", "-p"]
          readinessProbe:
            exec:
              command: ["smbstatus", "-p"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: operacoes
              mountPath: /operacoes
              readOnly: true
            - name: operacoes
              mountPath: /mnt/cloud/operacoes
              readOnly: true
            - name: home
              mountPath: /home
      volumes:
        - name: operacoes
          cephfs:
            monitors:
              - 192.168.2.42:6789
            user: admin
            secretRef:
              name: ceph-secret
            path: /operacoes
        - name: home
          cephfs:
            monitors:
              - 192.168.2.42:6789
            user: admin
            secretRef:
              name: ceph-secret
            path: /export/home
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
