apiVersion: v1
kind: Service
metadata:
  name: ssh
spec:
  selector:
    app: ssh
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ssh
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ssh
    spec:
      containers:
      - image: fedora/ssh
        imagePullPolicy: IfNotPresent
        name: ssh
        command: ["/entrypoint.sh"]
        args: ["/usr/bin/bash", "-c", "mkdir /root/.ssh; cp /tmp/ssh/authorized_keys /root/.ssh; chmod 700 /root/.ssh -R; /usr/sbin/sshd -D"]
        ports:
        - containerPort: 22
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/ssh
          name: ssh
      volumes:
      - name: ssh
        configMap:
          name: ssh
          defaultMode: 0400
