apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: rbd
parameters:
  adminSecretName: ceph-admin-secret
  adminSecretNamespace: default
  imageFeatures: layering
  imageFormat: "2"
  monitors: 192.168.2.42:6789
  userSecretName: ceph-user-secret
  userSecretNamespace: default
provisioner: ceph.com/rbd
reclaimPolicy: Delete
volumeBindingMode: Immediate
