apiVersion: v1
kind: Service
metadata:
  name: {{ include "sambarw1.fullname" . }}
  labels:
{{ include "sambarw1.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: smb
      protocol: TCP
      name: smb
  selector:
    app.kubernetes.io/name: {{ include "sambarw1.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
